apiVersion: v1
kind: Service
metadata:
  name: kube-manager
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "kube-manager.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
