replicaCount: 1

image:
  repository: localhost:32000/yaml-explainer
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080
env:
  OPENROUTER_API_KEY: "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"

