replicaCount: 1

image:
  repository: localhost:32000/kube-web
  tag: latest
  pullPolicy: Always

service:
  nodePort: 30080

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

grafana:
  url: "http://localhost:30090"
